### ISSUE TITLE
Packaging for openSUSE: compiling fails with "unresolved imports"

### ISSUE THREAD

**Issue by johanneskastl** [jetporch/jetporch#17]
### What Happened?

I am very excited to try this out. So, even though this is still early alpha, I wanted to package this for openSUSE.
https://build.opensuse.org/package/show/home:ojkastl_buildservice:Branch_systemsmanagement_ansible/jetporch

But the compilation fails with missing imports:

```
[   87s]    Compiling serde_yaml v0.9.25
[   87s]    Compiling guid-create v0.3.1
[   88s]    Compiling rayon v1.8.0
[   94s]    Compiling handlebars v4.4.0
[   97s]    Compiling ssh2 v0.9.4
[  104s]    Compiling rs_sha512 v0.1.3
[  105s]    Compiling inline_colorization v0.1.5
[  117s]    Compiling jetp v0.1.0 (/home/abuild/rpmbuild/BUILD/jetporch-v0.0.1)
[  118s] error[E0583]: file not found for module `version`
[  118s]   --> src/cli/mod.rs:20:1
[  118s]    |
[  118s] 20 | pub mod version;
[  118s]    | ^^^^^^^^^^^^^^^^
[  118s]    |
[  118s]    = help: to create the module `version`, create file "src/cli/version.rs" or "src/cli/version/mod.rs"
[  118s] 
[  118s] error[E0432]: unresolved imports `crate::cli::version::GIT_VERSION`, `crate::cli::version::GIT_BRANCH`, `crate::cli::version::BUILD_TIME`
[  118s]   --> src/cli/parser.rs:30:27
[  118s]    |
[  118s] 30 | use crate::cli::version::{GIT_VERSION,GIT_BRANCH,BUILD_TIME};
[  118s]    |                           ^^^^^^^^^^^ ^^^^^^^^^^ ^^^^^^^^^^ no `BUILD_TIME` in `cli::version`
[  118s]    |                           |           |
[  118s]    |                           |           no `GIT_BRANCH` in `cli::version`
[  118s]    |                           no `GIT_VERSION` in `cli::version`
[  118s] 
[  119s] Some errors have detailed explanations: E0432, E0583.
[  119s] For more information about an error, try `rustc --explain E0432`.
[  119s] error: could not compile `jetp` (bin "jetp") due to 2 previous errors
[  119s] error: Bad exit status from /var/tmp/rpm-tmp.4iMvGX (%build)
```

The build itself runs in an environment without internet connectivity. So before that all dependencies are being vendored using some cargo vendor functionality. This depends on cargo.lock as I understand it. Could it be that there is a dependency missing in this file (or the relevant file, in case I mixed up the file names)?

### Version

0.0.1 (Tech preview 1)

**Comment by mpdehaan** [comment]
I don’t underderstand this ticket - no packaging code exists in tree and you are filing a bug on this project about /your/ efforts to packaging it failing — so it can’t be a jetp bug right?

Please stop by Discord for questions and perhaps we can help you out but this isn’t bug territory.

build.rs runs version.sh, consult either to see what is going on there.

**Comment by johanneskastl** [comment]
Sorry for troubling you. I have no access to discord, hence the bug report. And I was not sure if this was bug in some of the dependencies that just went unnoticed. Or if there was something I was missing.

Basically all that is happening is that I am compiling jetporch and it fails. I do not need any packaging code upstream for this.

But ok, I'll ask in discord.

**Comment by johanneskastl** [comment]
Thanks for the hint regarding the version.sh script. I could solve this issue and jetporch is now compiling...

And yes, jetporch was innocent. It was just that git commands were not working inside the build environment, as source tarball was not containing a full git checkout...

Next up: Testing jetporch...

**Comment by mpdehaan** [comment]
Good deal, glad it got resolved!
