### ISSUE TITLE
jetp_ssh_hostname is not used?

### ISSUE THREAD

**Issue by Yethal** [jetporch/jetporch#5]
### Version

<-- paste the version/date info from 'jetp --version' -->
build a7a8ceb5e52e3d324c8aca0ce0ee49434c218f83@main
### Steps to Reproduce

1. In inventory create groups/all file
2. In inventory/groups/all add single host by name
3. In inventory/host_vars create file named after the host
4. In inventory/host_vars/host specify jet_ssh_hostname: IPADDRESSHERE
5. Try running a playbook targeting said host

### Additional Information

Works fine after the name of the host is set to its ip address which suggests we're hitting None case in src/playbooks/context.rs:309

**Comment by mpdehaan** [comment]
Thanks for reporting this, in the future, it is helpful if you can include the playbook output, but I know what this means so I can test.

This was functional for a while but it's not something I use regularly, so will see what's up!  Thanks!

**Comment by tonk** [comment]
I also ran into this, but for clarity: is the variable name `jet_ssh_hostname` or `jetp_ssh_hostname`?

**Comment by mpdehaan** [comment]
It's jet_

Also for my own not-forgetting, it looks like all these magic vars aren't being read, thanks for pointing that out!

**Comment by mpdehaan** [comment]
I pushed a fix in 42f92fb06244ac2c712b32c376850def0126fc64 ... also to correct myself from earlier, the port and user settings were being read, it was only the hostname that was not.
