### ISSUE TITLE
rs_sha512 has an incompatible license

### ISSUE THREAD

**Issue by amousset** [jetporch/jetporch#6]
The `rs_sha512` dependency has a [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html) license while jetporch is released under GPL 3.0. The author seems [open](https://github.com/Azgrom/RustyShield/issues/27) about considering other licenses, and there are also other more widely used implementations like the [sha2](https://crates.io/crates/sha2) crate.

**Comment by mpdehaan** [comment]
Hmm.... It's curious how poorly that is shown in the Crates system, I would have imagined all libraries would have had to be fairly unrestricted. 

That's unfortunate and we can stop using it.

Is this something you would like to work on?

**Comment by amousset** [comment]
sure, I can make a PR to switch to `sha2`.

**Comment by mpdehaan** [comment]
awesome, thank you!
